############################
## CHANGE THESE
############################

baseURL: 'https://harilvfs.github.io/hugoweb/'
title: 'aayush'

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


