############################
## Author
############################

author:
  name: "Aayush"
  image: author.jpeg
  greeting: "A personal blog for Hugo :evergreen_tree:"
  icon: ":wave:"

############################
## Links
############################

links:
  - github: https://github.com/aayushx402/
  # - facebook: https://github.com/chrede88/qubt
  - x-twitter: https://x.com/aayushxvf
  # - mastodon:
  - linkedin: https://linkedin.com/in/aayushchalese 
  - instagram: https://instagram.com/aayushxvf/
  - reddit: https://reddit.com/u/aayush-le/ 
  - telegram: https://t.me/aayushchalise 
  # - whatsapp: 
  # - signal: 
  # - codepen: 
  # - dev: 
  - email: aayushchalise8@gmail.com 
  - website: https://chalisehari.com.np/
  # - link: 
  - discord: https://discord.com/users/sheron_x
  # - orcid:
  # - slack:
  # - stack-overflow: 
  # - twitch: 
  # - patreon: 
  # - soundcloud:
  # - dribbble: 
  # - stack-exchange: 
  # - tiktok: 
  # - youtube:
  # - keybase: 
  # - flickr: 
  # - tumblr:
  # - kickstarter: 
  # - snapchat:
  # - bluesky: 
  # - bitbucket:
  # - bandcamp: 
  # - etsy: 
  # - spotify: 
  # - pinterest: 
  # - strava: 
  # - untappd: 
  # - skype: 
  # - medium: 
  # - foursquare: 
  # - apple: 
  # - amazon: 
  # - google: 
  # - paypal: 
  # - windows: 

###############################
## OpenGraph & Twitter Cards
###############################

title: "harilvfs"
description: "Site build with Qubt & Hugo"
images:
  - thumbnail.jpeg
