############################
## Author
############################

author:
  name: "Aayush"
  image: author.jpeg
  greeting: "A [PSU] blog for Hugo :evergreen_tree:"
  icon: ":wave:"

############################
## Links
############################

links:
  - github: https://github.com/harilvfs/
  # - facebook: https://github.com/chrede88/qubt
  - x-twitter: https://x.com/harilvfs
  # - mastodon:
  - instagram: https://instagram.com/harilvfs/
  - reddit: https://reddit.com/u/aayush-le/ 
  - telegram: https://t.me/harilvfs 
  # - whatsapp: 
  # - signal: 
  # - codepen: 
  # - dev: 
  - email: aayushchalise8@gmail.com 
  - website: https://chalisehari.com.np/
  # - link: 
  - discord: https://discord.com/invite/8NJWstnUHd
  # - orcid:
  # - slack:
  # - stack-overflow: 
  - twitch: https://www.twitch.tv/aayushchalese 
  # - patreon: 
  # - soundcloud:
  # - dribbble: 
  # - stack-exchange: 
  # - tiktok: 
  # - youtube:
  - keybase: https://keybase.io/harilvfs 
  # - flickr: 
  # - tumblr:
  # - kickstarter: 
  # - snapchat:
  # - bluesky: 
  # - bitbucket:
  # - bandcamp: 
  # - etsy: 
  # - spotify: 
  - pinterest: https://pin.it/7LVgxZUQG
  # - strava: 
  # - untappd: 
  # - skype: 
  - medium: https://medium.com/@aayushchalise 
  # - foursquare: 
  # - apple: 
  # - amazon: 
  # - google: 
  # - paypal: 
  # - windows: 

###############################
## OpenGraph & Twitter Cards
###############################

title: "harilvfs"
description: "Suckssss"
images:
  - thumbnail.jpeg
